<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>C2C.Cli</RootNamespace>
    <AssemblyName>c2c</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\C2C.Core\C2C.Core.csproj" />
    <ProjectReference Include="..\C2C.Infrastructure\C2C.Infrastructure.csproj" />
  </ItemGroup>

</Project>
